main:
	g++ -std=c++11 -o main main.o
compile:
	g++ -std=c++11 -c main.cpp
ceverything:
	del main.exe main.o kursiokai.txt Darbstuoliai.txt  Marozai.txt
cresults:
	del Darbstuoliai.txt Marozai.txt
cprogram:
	del main.exe main.o
cdata:
	del kursiokai.txt
